type(a)는 a에 대입된 값의 class(자료형)를 나타냄.
int는 정수, float는 소수를 의미.

In [3]:
a = 1; print(type(a))

<class 'int'>


a에 대입된 값은 1로 같지만 a가 float함수의 값을 가지므로 a의 class는 float임.

In [18]:
a = 1; a = float(a); print(type(a))

<class 'float'>


마찬가지로 a에 1.2 가 대입되었지만 a는 int함수의 값을 가지므로 class는 int로 나옴.

In [19]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


'123'에서 123은 연산이 안되는 문자, string을 의미.
a='123'에서 '123'의 첫번째 문자만 가져오고 싶을 때는

In [6]:
a = '123'; print(a[0])

1


파이썬에서 string의 n번째 문자를 가져오고 싶을 때는 대괄호 안에 n-1의 값을 입력.

In [20]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


단 a[-1]은 마지막 번째 문자를 의미.

In [16]:
a = '123'; print(a[-1])

3


string인 a를 list로 표현. string은 'abc'로 list는 [a,b,c]로 표현.

In [8]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


list는 대괄호로 tuple은 소괄호로 표현.

In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


dictionary를 통해 여러 대응관계를 동시에 나타낼 수 있음.

In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


In [22]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

numpy라는 폴더를 불러와서 그 안에 있는 array라는 함수를 사용하려함.
이때 numpy 를 np로 지정하여 계속해서 numpy라고 쓸 필요가 없어짐.
a에 array함수를 적용하여 나온 값인 b는 numpy.ndarry class로 분류.

In [23]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


이때 array는 사실 행렬이 아니므로 곱셈 연산 시 행렬의 규칙을 따르지 않음.

In [24]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


array인 b를 matrix인 c로 변환.

In [25]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


c는 행렬이고 2x3 행렬끼리는 곱셈이 불가능하므로 c끼리의 곱셈도 불가능.

In [26]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

행렬의 곱셈을 가능하게 하기위해 transpose를 이용.

In [27]:
c*c.T

matrix([[14, 19],
        [19, 73]])